### ISSUE TITLE
Provide a binary executable for downloading.

### ISSUE THREAD

**Issue by corvus1** [unxed/dn2l#8]
Is there a chance I could download the executable, without having to build it myself? init.sh currently doesn't work, because apparently it's not aware of case-sensitive filesystems. It's trying to call vp, but it's really VP, and I made a bunch of symlinks, but something else refused to work, it's just a bit too much. 

But I'd love to see DN again for nostalgia reasons, especially the tetris. :-D

**Comment by unxed** [comment]
http://2g0.ru/tmp/dn2l.tar.gz

**Comment by unxed** [comment]
But it is VERY experimental, just for nostalgia you'd better try win32 version in wine :)

btw, what operating system exactly you are using?

**Comment by corvus1** [comment]
> But it is VERY experimental, just for nostalgia you'd better try win32 version in wine :)
> 
> btw, what operating system exactly you are using?

I'm currently using gentoo linux.

**Comment by corvus1** [comment]
And where can I get a pre-compiled win32 version?

**Comment by unxed** [comment]
> And where can I get a pre-compiled win32 version?

http://dnosp.com/files/dn2/dn2w214.rar

**Comment by corvus1** [comment]
Thank you.
